### ISSUE TITLE
Invalid Mechanism

### ISSUE THREAD

**Issue by Green-EyE** [jason-p-pickering/datim-validation#21]
Hi Jason
I'm running " getInvalidMechanisms(d,base.url,username,password,organisationUnit, validityDate ='2016-09-29')" and it's returning one invalid Mechanism "18275". But I can see it on Datim Pivot table.

Can I have your assistance , please ?
![image](https://cloud.githubusercontent.com/assets/8640356/17129422/4e0ce4cc-5313-11e6-9d03-94ac57c63b14.png)
 
Thanks
G

**Comment by jason-p-pickering** [comment]
@Green-EyE , mechanisms have validity for specific periods. They will always be available through the Pivot Table, but may not be valid for data import for specific periods (or at all) . 

Which period are you attempting to import data for? There may be a bug in this method, which does not correctly identify the period's start and end dates, and how they relate to the mechanism.

**Comment by Green-EyE** [comment]
Thanks, we are attempting for 2016Q2.

G

**Comment by jason-p-pickering** [comment]
I cannot reproduce your error with a test file. 

Please execute the "clearCache()" command and be sure you get a recent copy of the metadata. I cannot reproduce your error with a test file, but this is a known limitation with this method. 

This is related to #17, whereby periods such as 2016Q2 should really have an end-date of 2016-06-30 instead of 2016-09-29, which is the default. You can however specify the end-date of your period to check and see if the mechanism is considered to be valid. For instance in this case, it would be 

getInvalidMechanisms(d,base.url,username,password,organisationUnit, validityDate ='2016-06-30')

which is the end-date of 2016Q2. (Remember we are using calendar quarters, not financial year quarters). 

However, the default end-date is actually greater than the end-date of your data, so that would not really help here, but just thought I should high-light that. 

I suspect you have some cached metadata. Please execute the "clearCache()" command from the R terminal, answer "Y" and all cached metadata should be cleared. You can then start your script again.

**Comment by Green-EyE** [comment]
Hi Jason
I've followed your advise and I still facing the same problem. Also I've ran "Valid_IM <- getMechanismsMap(base.url,username,password,organisationUnit,endDate="2016-09-30") and 18275 is not listed.

Should I open a DATIM ticket and ask the team to add it ?

G

**Comment by Green-EyE** [comment]
Hi JP
I was able to retrieve all my organisation unit Implementing Mechanismsby browsing https://www.datim.org/api/categoryOptions?filter=organisationUnits.id:eq:myorgunitid&paging=false
 and all the Invalid Mechanism retrieved using this R Script are there. Seems to me that the new synchronized IM's are  been cached by the Script as Invalid Mechanism

It's possible to update the script in order to  approve those new existing Implementing Mechanisms ?

Thanks
G
