### ISSUE TITLE
validateData issues - on Windows 

### ISSUE THREAD

**Issue by mmwebaze** [jason-p-pickering/datim-validation#35]
@jason-p-pickering writing validateData returned validation.results into a csv file both orgUnit and attributeOptionCombo are NA in the resultant validation_violations csv file.

**Comment by jason-p-pickering** [comment]
@mmwebaze I need more details. Could you provide details of a data file to test?

**Comment by mmwebaze** [comment]
@jason-p-pickering 

I have been able to isolate the issue. When validating a file, if a facility doesn't have a code, NA is used in the resultant violations file. Ticket #6367 on helpdesk has a sample data file which can be used to replicate this issue. 

FYI @ManishUNC

**Comment by jason-p-pickering** [comment]
Good find. I will take a look tomorrow. I think it makes sense however.

**Comment by stephbruno** [comment]
Thanks for the help!  If you could include both the id and the code for an organization then we would be all set.

**Comment by stephbruno** [comment]
Is there any update on this?  The validation script is still returning blanks for us because some of our org units are missing codes.  Could you please include the org unit id as well?
Thank you!

**Comment by jason-p-pickering** [comment]
@stephbruno I think this has been fixed with a tighter validation of the import file. If your file has any codes which are missing, and the coding scheme has been set to code, you will get an error. This has been implemented here d9d88e64393576291d8526e6ca5d65923fffe7bb and will be merged into the master branch soon. However, if you want to test it , please feel free to try from the `unit-tests` branch.
