### ISSUE TITLE
validating mechanisms

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#41]
Hey Jason,

checkMechanismPeriodValidity says: "This function will return an object of invalid mechanisms and periods"; but when running with a file that has an invalid mechanism (when importing file that has code for mechanisms, it converts all valid mechanisms to UIDs, but invalid stays same - e.g. I put in 17x269) it only flags periods, but does not flag invalid mechanisms.

sims parser flags invalid mechanisms on import, and shows a warning that record is being excluded, while d2parser imports it and checkMechanismPeriodValidity does not flag it.

Thanks,
Vlad

**Comment by jason-p-pickering** [comment]
Yup. I see it. This is part of a bigger refactor, but will fix this ASAP.

**Comment by jason-p-pickering** [comment]
@vshioshvili I think this has been fixed in the unit-tests branch here d9d88e64393576291d8526e6ca5d65923fffe7bb. 

What will happen now is if the file is able to be parsed, but if we are not able to remap everything to UIDs, we should error out. This could happen for instance when people supply the wrong coding scheme, or if they use the correct coding scheme, but the identifiers do not exist. 

This is really a pretty superficial check. It will not check things like data element/cat option combo associations, which will be handled separately. This is only for checking that we can produce a valid data frame, which should consist of only UIDs which actually exist and are valid.
